{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cards-api
  labels:
    {{- include "cards-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cards-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
