name: ci

on:
  pull_request:
  push:
    branches: [main]

env:
  GOPROXY: direct
  GONOSUMDB: github.com/demo-org-np-migration

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test ./... -v

  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/setup-helm@v4
        with:
          version: v3.17.2

      - name: helm lint
        run: helm lint deploy/chart

      - name: helm template (staging)
        run: helm template cards-api deploy/chart -f deploy/values-staging.yaml
